config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  
  resources :strategies

  resources :users do 
    resources :strategies
    resources :actions
  end
  resources :actions

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  
end

app/models/action.rb
class Action < ApplicationRecord
    has_many :strategies
    has_many :users, through: :strategies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/strategy.rb
class Strategy < ApplicationRecord
  belongs_to :user
  belongs_to :action
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, :presence => true 
    validates :email, :presence => true, :uniqueness => true
    validates :password, :presence => true, :length => {:minimum => 3}
    
    has_secure_password

    has_many :strategies
    has_many :actions, through: :strategies


    def adjust_for_taxes
        case self.salary

        when (10001..40000)
            taxable_amount = self.salary - 10000
            money_to_sam = taxable_amount * 0.13 + 1000
            money_to_ss = self.salary * 0.0145
            money_to_medicare = self.salary * 0.029
            nonsense_money = money_to_medicare + money_to_ss + money_to_sam
            self.salary = self.salary - nonsense_money.round(2)
        when (40001..90000)
            taxable_amount = self.salary - 40000
            money_to_sam = taxable_amount * 0.23 + 4700
            money_to_ss = self.salary * 0.0145
            money_to_medicare = self.salary * 0.029
            nonsense_money = money_to_medicare + money_to_ss + money_to_sam
            self.salary = self.salary - nonsense_money.round(2)
        when (90001..180000)
            taxable_amount = self.salary - 90000
            money_to_sam = taxable_amount * 0.25 + 14700
            money_to_ss = self.salary * 0.0145
            money_to_medicare = self.salary * 0.029
            nonsense_money = money_to_medicare + money_to_ss + money_to_sam
            # binding.pry
            self.salary = self.salary - nonsense_money.round(2)
        when (180001..300000)
            taxable_amount = self.salary - 180000
            money_to_sam = taxable_amount * 0.33 + 33000
            money_to_ss = self.salary * 0.0145
            money_to_medicare = self.salary * 0.029
            nonsense_money = money_to_medicare + money_to_ss + money_to_sam
            self.salary = self.salary - nonsense_money.round(2)
        when (300001..500000)
            taxable_amount = self.salary - 300000
            money_to_sam = taxable_amount * 0.35 + 48000
            money_to_ss = self.salary * 0.0145
            money_to_medicare = self.salary * 0.029
            nonsense_money = money_to_medicare + money_to_ss + money_to_sam
            self.salary = self.salary - nonsense_money.round(2)
        else (0..10)
            money_to_sam = self.salary * 0.1
            money_to_ss = self.salary * 0.0145
            money_to_medicare = self.salary * 0.029
            nonsense_money = money_to_medicare + money_to_ss + money_to_sam
            self.salary = self.salary - nonsense_money.round(2)
        end
    end

    # def medicare_tax(salary)
    #     ss_and_medicare = (salary * social_security_tax) + (salary * medicare_tax(salary))
    #     if salary <= 200000
    #         medicare_tax = 0.0145
    #     else
    #         medicare_tax = 0.029 
    #     end 
    #     medicare_tax
    # end

    # def social_security_tax
    #     social_security_tax = 0.062
    # end
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
    def show
        if params[:user_id] && @user = User.find_by(:id => params[:user_id])
            if @user.actions.any?
                @action = @user.actions.find_by(:id => params[:id])
            else
                @action = Action.find_by(:id => params[:id])
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        user = User.find_by(:email => params[:email])
        if user && user.authenticate(params[:password])
           session[:user_id] = user.id
           redirect_to user_path(user)
        else
            flash[:alert] = "Unable to find user"
            redirect_to login_path
        end
    end

    def destroy
        redirect_to root_path if session.clear
    end
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
    
    def show
        if session[:user_id] && @user = User.find_by(:id => params[:user_id])
            @strategy = @user.strategies.find_by(:id => params[:id])
        else
            flash[:error] = "STRATEGIES CAN ONLY BE VIEWED BY THEIR CREATOR"
            redirect_to root_path
        end
    end
    
    def new
        if session[:user_id] && @user = User.find_by(:id => params[:user_id])
            @strategy = @user.strategies.build
            @actions = Action.all
        else 
            flash[:alert] = "Must be a user"
            redirect_to root_path
        end
    end

    def create
        if @user = User.find_by(:id => strategies_params[:user_id])
            @strategy = @user.strategies.build(strategies_params)
            if @strategy.save
                redirect_to user_path(@user)
            else 
                redirect_to root_path
            end
        end 
    end

    private

    def strategies_params
        params.require(:strategy).permit(:goal,:path,:amount,:user_id,:action_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    helper_method :current_user
    
    def index
    end

    def show
        if session[:user_id] && @user = User.find_by(:id => params[:id])
            @actions = Action.all
        else 
            redirect_to root_path
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else            
            @errors = @user.errors.full_messages
            render :new
        end
    end
    
    def edit
        if session[:user_id] && @user = User.find_by(:id => params[:id])
            @user
        end
    end
    
    def update
        if session[:user_id] && @user = User.find_by(:id => params[:id])
            @user.update(user_params)
            if @user.save
                redirect_to user_path(@user)
            else
                redirect_to root_path
            end
        end   
    end
    
    
    private

    # def current_user
    #     if session[:user_id] && @user = User.find_by(:id => params[:id])
    #         @actions = Action.all
    #     else 
    #         redirect_to root_path
    #     end
    # end

    def user_params
        params.require(:user).permit(:name,:email,:salary,:password)
    end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/strategies_helper.rb
module StrategiesHelper
    # def display_new_strategy(@user)
    #     link_to "New Strategy", new_user_strategy_path(@user)
    # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actions/show.erb
<h1><%= @action.name %></h1>

<% if @action.strategies.any? %>
    <% @action.strategies.each do |s| %>
        <%= link_to "#{s.goal} - #{s.user.name}", user_strategy_path(s) %><p>
    <% end %>
        <%= link_to "DASHBOARD", user_path() %> |
        <%= link_to "NEW", new_user_strategy_path() %>

<% end %>

<%= link_to "DASHBOARD", user_path(params[:user_id]) %>
<%= link_to "NEW", new_user_strategy_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCoins</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/strategies/new.erb
<%= form_for(@strategy) do |f| %>
    <%= f.hidden_field :user_id, :value => @strategy.user.id %>
    Choose your plan of action: <%= f.collection_select :action_id, @actions, :id, :name%><p>
    Goal: <%= f.text_field :goal %>
    Path: <%= f.text_field :path %>
    Amount: $<%= f.number_field :amount %>
    <%= f.submit "Create Strategy" %>
<% end %>

app/views/strategies/show.erb
<%# SHOW AMOUNT FOR AN ACTION %>




<%= @strategy.goal %>
<p>
<%= @strategy.path %>
<p>
<%= @strategy.amount %>
<p>
<%= link_to "DASHBOARD", user_path(@strategy.user) %>

app/views/users/edit.erb
<%= form_for(@user) do |f| %>
    SALARY: <%= f.number_field :salary %>
    PASSWORD: <%= f.password_field :password %>
    <%= f.submit "Submit"%>
<% end %>

app/views/users/index.erb
<%= flash[:error] if true %>
<p>

Welcome to MyCoins 
<p>

<%= link_to "Sign Up", new_user_path %> | 
<%= link_to "Log In", login_path %>

app/views/users/new.erb
<% if @errors %>
  <div id="error_explanation">
    <h2><%= pluralize(@errors.count, "error") %> prohibited you from saving this profile:</h2>
    <ul>
      <% @errors.each.uniq do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@user) do |f| %>
    Name: <%= f.text_field :name %>
    Password: <%= f.password_field :password %>
    Email: <%= f.email_field :email %>
    <%= f.submit "Create User" %>
<% end %>

app/views/users/show.erb
<%= @user.name.upcase %> | SALARY 
<p>
TO SIMPLIFY FOR PURPOSES OF THIS APP, TAXES ARE BASED ON A SINGLE FILER. 
<p>
SOCIAL SECURITY AND MEDICARE HAVE ALSO BEEN TAKEN INTO ACCOUNT. 
<p>
THIS IS YOUR ~NET INCOME 
$<% if @user.salary == 0 %>
    <h3>Salary hasn't been set. Set now.</h3>
    <%= form_for(@user) do |f| %>
        Salary: <%= f.text_field :salary %>
        Confirm Password: <%= f.password_field :password %>
        <%= f.submit "Update Salary" %>
    <% end %>
   <% else %>
   <%# MAKE HELPER METHOD TO MOVE MODEL METHOD OUT OF VIEW %>
    <%= @user.adjust_for_taxes %>
<% end %>


<p>
CURRENT EMAIL: <%= @user.email %>
<p>
DASHBOARD:
<p>
    <% @actions.each do |action| %>

        <%= link_to action.name, user_action_path(@user,action) %> |<br> 

        <ul><% action.strategies.each do |s| %>
        
            <li><%= s.goal %></li><p>
        
        <% end %></ul>

    <% end %>


    <%= link_to "EDIT", edit_user_path(@user) %> |
    <%= link_to "LOGOUT", logout_path, :method => 'delete' %> 